"""Add risk management program models

Revision ID: 34558889d887
Revises: 
Create Date: 2025-09-22 12:25:26.385443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34558889d887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
