"""Add category, impact, and actions_taken columns to alerts table

Revision ID: 3bd74d8f60ad
Revises: 2ee24d3fafd0
Create Date: 2025-10-22 17:06:55.265447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd74d8f60ad'
down_revision = '2ee24d3fafd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('impact', sa.String(length=20), nullable=True, server_default='low'))
    op.add_column('alerts', sa.Column('actions_taken', sa.Text(), nullable=True))
    op.alter_column('compliance_incidents', 'incident_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('retention_config', 'auto_purge',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retention_config', 'auto_purge',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('compliance_incidents', 'incident_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('alerts', 'actions_taken')
    op.drop_column('alerts', 'impact')
    op.drop_column('alerts', 'category')
    # ### end Alembic commands ###
