"""Add mitigation plan caching fields

Revision ID: 56aedba3d364
Revises: 5fd04cfb0c8a
Create Date: 2025-09-17 12:46:46.108046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56aedba3d364'
down_revision = '5fd04cfb0c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('mitigation_plan_json', sa.Text(), nullable=True))
    op.add_column('risks', sa.Column('mitigation_plan_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'mitigation_plan_updated')
    op.drop_column('risks', 'mitigation_plan_json')
    # ### end Alembic commands ###
