"""Add impact column to alerts

Revision ID: 5a6f6c12291b
Revises: 3bd74d8f60ad
Create Date: 2025-10-23 11:24:04.498704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6f6c12291b'
down_revision = '3bd74d8f60ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('impact', sa.String(length=20), nullable=True, server_default='low'))
    op.add_column('alerts', sa.Column('actions_taken', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'actions_taken')
    op.drop_column('alerts', 'impact')
    # ### end Alembic commands ###
