"""Add auto_purge field to RetentionConfig

Revision ID: 9cac64371aed
Revises: a422d60f9325
Create Date: 2025-10-14 13:28:01.869532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cac64371aed'
down_revision = 'a422d60f9325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retention_config', sa.Column('auto_purge', sa.Boolean(), nullable=True, default=False))
    # Set default value for existing rows
    op.execute("UPDATE retention_config SET auto_purge = 0 WHERE auto_purge IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retention_config', 'auto_purge')
    # ### end Alembic commands ###
