"""Add monitoring configuration model

Revision ID: a422d60f9325
Revises: add_missing_risk_fields
Create Date: 2025-10-07 12:44:25.078660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a422d60f9325'
down_revision = 'add_missing_risk_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
