"""Add created_at and updated_at to User model

Revision ID: ad85fe641eec
Revises: 
Create Date: 2025-09-11 14:28:51.442597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad85fe641eec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable (SQLite doesn't support ALTER COLUMN)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Populate existing rows with current timestamp
    from datetime import datetime, timezone
    current_time = datetime.now(timezone.utc)

    # Update existing users with current timestamp
    op.execute(f"UPDATE users SET created_at = '{current_time.isoformat()}' WHERE created_at IS NULL")
    op.execute(f"UPDATE users SET updated_at = '{current_time.isoformat()}' WHERE updated_at IS NULL")

    # Note: For SQLite, we keep columns nullable in migration.
    # The SQLAlchemy model will enforce NOT NULL for new records.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
