title: "My GitHub Pages Site"
description: "Simple documentation site with markdown"

theme: minima

header_pages:
  - index.md
  - about.md
  - projects.md
  - resume.md
  - contact.md

author:
  name: "Saroj Kushwaha"
  email: "kush786srj@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fa-linkedin"
      url: "https://www.linkedin.com/in/saroj-kushwaha-7ba25726a"

logo: "/assets/img/dae-web.png"
